config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  broadcasts
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[new create]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.turbo_stream
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HotwireSample
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = yield :head
    = stimulus_include_tags
  %body
    = yield

app/views/messages/_message.html.haml
%p{ id: dom_id(message) }
  #{message.created_at.to_s(:short)}: #{message.content}

app/views/messages/new.html.haml
%h1 New Message

= turbo_frame_tag 'new_message', target: '_top' do
  = form_with(model: [@message.room, @message], data: { controller: 'form', action: 'turbo:submit-end->form#reset' }) do |f|
    .field
      = f.text_field :content, data: { action: 'keyup->form#preview' }
      = f.submit 'Send'
    %pre{ data: { 'form_target': 'preview' }}


= link_to 'Back', @message.room

app/views/rooms/_form.html.haml
= form_for @room do |f|
  - if @room.errors.any?
    #error_explanation
      %h2= "#{pluralize(@room.errors.count, "error")} prohibited this room from being saved:"
      %ul
        - @room.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/rooms/_room.html.haml
%p{ id: dom_id(room) }
  %strong Name:
  = room.name

app/views/rooms/edit.html.haml
%h1 Editing room

= turbo_frame_tag 'room' do
  = render 'form'
  %my-app
  = react_component 'HelloWorld'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Listing rooms

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @rooms.each do |room|
      %tr
        %td= room.name
        %td= link_to 'Show', room
        %td= link_to 'Edit', edit_room_path(room)
        %td= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New room

= render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p#notice= notice

= turbo_stream_from @room

Renderd at #{l Time.current}
= turbo_frame_tag 'room' do
  = render @room

  = link_to 'Edit', edit_room_path(@room)
  \|
  = link_to 'Back', rooms_path, target: '_top'
#messages
  = render @room.messages
= turbo_frame_tag 'new_message', src: new_room_message_path(@room)